### ISSUE TITLE
所有的json都加omitempty不適用，有些值是0，會被omitempty標籤給遮罩掉

### ISSUE THREAD

**Issue by pylist** [teacat/shopeego#4]
比如GetItemsList裡面的pagination_offset，當時當獲取第一頁的時候值為0，它會被omitempty標籤給遮罩，api會提示我缺少必須參數pagination_offset

**Comment by YamiOdymel** [comment]
蝦皮的文件真的爛到會害死人，那我會先把 GetItemsList 的 Offset 的 omitempty 拿掉。

或者如果你能力足夠的話，也可以推 Pull Request 上來

**Comment by pylist** [comment]
可以，等我寫完手上的項目，我Pull一份上來，一起完善一下
