### ISSUE TITLE
GetOrderDetails方法解析JSON失败

### ISSUE THREAD

**Issue by pylist** [teacat/shopeego#6]

**Comment by YamiOdymel** [comment]
又是 

```
json: invalid use of ,string struct tag, trying to unmarshal unquoted value into float64
```

錯誤嗎 🤔

**Comment by pylist** [comment]
> 又是
> 
> ```
> json: invalid use of ,string struct tag, trying to unmarshal unquoted value into float64
> ```
> 
> 錯誤嗎 🤔

对, 还是这个错误

**Comment by YamiOdymel** [comment]
噢…我調查之後看起來關鍵字都有正確地被處理（看起來啦）

然後我想到你提交的那份 Pull Request 把 `replaceConcat` 那部份註釋掉了，可能是因為這樣造成你發生

```
json: invalid use of ,string struct tag, trying to unmarshal unquoted value into float64
```

的錯誤，因為那部份就是為了 Patch 這個錯誤才寫的，所以你可以考慮先移除註釋看看

**Comment by pylist** [comment]
> 噢…我調查之後看起來關鍵字都有正確地被處理（看起來啦）
> 
> 然後我想到你提交的那份 Pull Request 把 `replaceConcat` 那部份註釋掉了，可能是因為這樣造成你發生
> 
> ```
> json: invalid use of ,string struct tag, trying to unmarshal unquoted value into float64
> ```
> 
> 的錯誤，因為那部份就是為了 Patch 這個錯誤才寫的，所以你可以考慮先移除註釋看看
> 
> 我這裡的話目前因為 Shopee 吐出什麼 error_cache 的錯誤害我沒辦法實際開一個 Test Shop 來測試，所以只好先盲測了。

sorry, 確實是這個問題，我把注釋取消掉就沒問題了，搞不懂蝦皮的注釋



但是我發現`GetItemDetail`這個方法依舊報錯

然後我找到`GetItemDetailResponseItemAttribute.AttributeName`

我看官方檔案解釋的uint32類型，這裡是`int`類型，但是實際返回值是`string`類型  
```
type GetItemDetailResponseItemAttribute struct {
	// The Identify of each category
	AttributeID int64 `json:"attribute_id,omitempty"`
	// The name of each attribute
	AttributeName string `json:"attribute_name,omitempty"`
	// This is to indicate whether this attribute is mandantory
	IsMandatory bool `json:"is_mandatory,omitempty"`
	// Enumerated type that defines the type of the attribute. Applicable values: See Data Definition- AttributeType.
	AttributeType string `json:"attribute_type,omitempty"`
	// The value of this item attribute.
	AttributeValue string `json:"attribute_value,omitempty"`
}
```
這樣測試可以正常使用

**Comment by YamiOdymel** [comment]
新的 Commit 會加一下為什麼要實作那個 Patch 的緣由。順便看了一下所有跟 `attribute_name` 有關的 API：

* [shopee.item.Add](https://open.shopee.com/documents/?type=1&module=2&id=365) / AddResponseItemAttribute
* [shopee.item.GetAttributes](https://open.shopee.com/documents/?type=1&module=2&id=372) / GetAttributesResponseAttribute
* [shopee.item.UpdateItem](https://open.shopee.com/documents/?type=1&module=2&id=376) / UpdateItemResponseItemAttribute
* [shopee.item.GetItemDetail](https://open.shopee.com/documents/?type=1&module=2&id=374) / GetItemDetailResponseItemAttribute

Shopee 文件上都寫 `uint32`，但是文件上這些欄位的 `Sample` 卻都又是字串值。

已經送了一個 Commit 把這些資料型態從 `int` 改為 `string` 了
