### ISSUE TITLE
有沒有api直接生成寄件單的PDF，我沒有找到他

### ISSUE THREAD

**Issue by pylist** [teacat/shopeego#7]

**Comment by YamiOdymel** [comment]
具我所知是沒有，你需要自己透過 Workaround 去偵測 Shopee 的出貨單網址，甚至傳送什麼 Cookie 給那些網址。

這是我自己這邊的作法，整個運作模式就是很複雜就是了（所以我也沒有辦法貼範例程式碼給你看）而且寄件單有時候還會出問題。

**Comment by pylist** [comment]
> 具我所知是沒有，你需要自己透過 Workaround 去偵測 Shopee 的出貨單網址，甚至傳送什麼 Cookie 給那些網址。
> 
> 這是我自己這邊的作法，整個運作模式就是很複雜就是了（所以我也沒有辦法貼範例程式碼給你看）而且寄件單有時候還會出問題。

蝦皮沒有提供運單圖片的url連接，那麼我需要自己去寫個爬蟲，類比登入然後抓取PDF運單

**Comment by YamiOdymel** [comment]
@pylist 對，就是這種煩躁的事情（如果你真需要一個爬蟲，或許可以參考看看用 Node.js 的 [`puppeteer`](https://www.npmjs.com/package/puppeteer) 去遙控一個 Chrome-headless 操作，因為多數情況下爬蟲可能需要支援 JavaScript；但不一定啦，可以參考。）

就算 [`shopee.logistics.GetOrderLogistics`](https://open.shopee.com/documents?module=3&type=1&id=385) 雖然有提供寄件單資訊，但也是非常非常地有限。例如說：其寄件條碼只有台灣服務範圍才能使用，而且僅支援兩種超商。

所以…爬蟲確實是一個最好但也更麻煩的辦法。

**Comment by pylist** [comment]
> @pylist 對，就是這種煩躁的事情（如果你真需要一個爬蟲，或許可以參考看看用 Node.js 的 [`puppeteer`](https://www.npmjs.com/package/puppeteer) 去遙控一個 Chrome-headless 操作，因為多數情況下爬蟲可能需要支援 JavaScript；但不一定啦，可以參考。）
> 
> 就算 [`shopee.logistics.GetOrderLogistics`](https://open.shopee.com/documents?module=3&type=1&id=385) 雖然有提供寄件單資訊，但也是非常非常地有限。例如說：其寄件條碼只有台灣服務範圍才能使用，而且僅支援兩種超商。
> 
> 所以…爬蟲確實是一個最好但也更麻煩的辦法。
这真是一件很麻烦很糟糕的事

**Comment by g-pyusr** [comment]
![image](https://user-images.githubusercontent.com/43725565/111735570-3553a900-88b7-11eb-85ed-e42c6cc935f9.png)

這確實很麻煩，還有一個問題，產生寄件編號這個功能對應的哪一個api，我找了訂單模塊和物流模塊都沒有發現

**Comment by YamiOdymel** [comment]
@g-pyusr 根據 Shopee 官方的 API 文件表示要[出貨的流程](https://open.shopee.com/documents?module=63&type=2&id=54&version=1)應該是這樣：

![image](https://user-images.githubusercontent.com/7308718/111735921-cd519280-88b7-11eb-96cc-f5eac6c5e2f4.png)

先呼叫 GetOrderByStatus 查看是否可出貨，然後透過 GetLogisticInfo 取得出貨資訊，接下來透過 Init 產生出貨寄件編號。
