### ISSUE TITLE
我有個疑問，為什麼我獲取訂單的用戶地址資訊，很多中間部分用*星號隱藏了，是我使用的api方法不對麼

### ISSUE THREAD

**Issue by pylist** [teacat/shopeego#8]

**Comment by YamiOdymel** [comment]
沒有，Shopee 為了保障使用者的權益，所以 API 取得資料的時候不會全部顯示。你可能要拿 Logistic 的相關資料，但是我怎麼記得那個資料的收件人名稱也是被 * 號保護的。

**Comment by pylist** [comment]
> 沒有，Shopee 為了保障使用者的權益，所以 API 取得資料的時候不會全部顯示。你可能要拿 Logistic 的相關資料，但是我怎麼記得那個資料的收件人名稱也是被 * 號保護的。

是的, 姓名, 手机号, 地址都被有部分被*号隐藏, 有办法可以获取到完整的信息么, 我看别人的网址是可以获取
